---
title: "yolanda"
author: "Bernard"
date: "2022-10-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


## Load package

```{r}
library(tidyverse)
library(data.table)
library (cowplot)
library (officer)
library (flextable)
library (dataPreparation)
library (correlation)

# ML
library(DHARMa)
library (bnlearn)
library (bootStepAIC)
library(MASS)

# Table
library (gtsummary)
library(GGally)
```

## Import data

```{r}
df <- rio::import ("data/WAD AND PAIN DATABASE_ T1 T2 T3-2.xlsx")
df <- janitor::clean_names(df)
```

# Explore

```{r}
skimr::skim (df)

mice::md.pattern(df, rotate.names = TRUE)

df <- na.omit(df)

new_names <- c("gender",
               "age",
               "sick_leave",
               "contract",
               "acc_wks",
               "area",
               "vehicle",
               "position",
               "rx",
               "rx_t2",
               "rx_t3",
               "education",
               "vas",
               "vas_t2",
               "vas_t3",
               "expect",
               "expect_t2",
               "expect_t3",
               "rec_t2",
               "rec_t3",
               "lotr",
               "cdse",
               "tsk",
               "pcs",
               "ndi",
               "ndi_t2",
               "ndi_t3")

names(df) <- new_names

correlation (df)

df <- df %>%
  mutate_if(is.character, as.factor) %>%
  mutate (vas_t3 = ifelse (vas_t3 == "1'5", "1.5", vas_t3),
          vas_t3 = as.numeric (as.character (vas_t3))) 
```



# Bayesian network

## Blacklist

```{r, eval = FALSE}

base_vars = c("gender")
t0_var <- c("vas", "expect", "lotr", "cdse", "ndi", "tsk", "pcs")
t2_var <- c("vas_t2", "expect_t2", "ndi_t2", "rec_t2")
t3_var <- c("vas_t3", "expect_t3", "ndi_t3", "rec_t3")


tiers_bl = list (base_vars, #to
                 c(t0_var, t2_var, t3_var)) #from
bl_1 = tiers2blacklist(tiers = tiers_bl)

tiers_bl = list (t0_var, #to
                 c(t2_var, t3_var)) #from
bl_2 = tiers2blacklist(tiers = tiers_bl)

tiers_bl = list (t2_var, #to
                 t3_var) #from
bl_3 = tiers2blacklist(tiers = tiers_bl)

bl <-  rbind(bl_1, 
           bl_2, 
           bl_3)  

bl
```

## Do bn analysis
 
```{r, eval = FALSE}

df_bn <- df %>%
  dplyr::select(all_of (c(base_vars, t0_var, t2_var, t3_var))) %>%
  mutate (expect = ifelse (expect > 90, "1", "0"),
          lotr = ifelse (lotr > 18, "1", "0"),
          cdse = ifelse (cdse > 25, "1", "0"),
          tsk = ifelse (tsk > 29, "1", "0"),
          pcs = ifelse (pcs > 15, "1", "0"),
          vas = ifelse (vas > 6, "1", "0"),
          ndi = ifelse (ndi > 15, "1", "0"),
          expect_t2 = ifelse (expect_t2 > 90, "1", "0"),
          ndi_t2 = ifelse (ndi_t2 > 3, "1", "0"),
          vas_t2 = ifelse (vas_t2 > 2, "1", "0"),
          rec_t2 = ifelse (rec_t2 > 85, "1", "0"),
          rec_t3 = ifelse (rec_t3 > 85, "1", "0"),
          expect_t3 = ifelse (expect_t3 > 90, "1", "0"),
          vas_t3 = ifelse (vas_t3 > 4, "1", "0"),
          ndi_t3 = ifelse (ndi_t3 > 3, "1", "0"),
          gender = factor (gender)) %>%
  mutate_if (is.character, factor)


skimr::skim (df_bn)


boot.list <-boot.strength(df_bn,
                         R = 1000,
                         algorithm = "hc",
                         algorithm.args = list (blacklist = bl))
  
avg.list <- averaged.network(boot.list, threshold = 0.5)
fit.list = bn.fit (avg.list, df_bn)

g = strength.plot(avg.list, 
                  boot.list, 
                  layout = "fdp",
                  shape = "rectangle")
graph::nodeRenderInfo(g) = list(fontsize=18)
Rgraphviz::renderGraph(g)
```

# Prognosis

```{r}
pred <- c("gender",
           "age",
           "sick_leave",
           "contract",
           "acc_wks",
           #"area",
           #"vehicle",
           #"position",
           "rx",
           "education",
           "vas",
           "expect",
           "lotr",
           "cdse",
           "tsk",
           "pcs",
           "ndi"
          )

fac_var <- c("gender",
           "sick_leave",
           "contract",
           # "area",
           # "vehicle",
           #"position",
           "rx",
           "education")

df2 <- df %>%
  dplyr::select(pred) %>%
  #mutate(contract = ifelse (contract == "1+2", "2", contract)) %>%
  mutate_at(vars(fac_var), factor) %>%
  mutate (education = fct_collapse(education,
                                   "1" = c("1", "2"),
                                   "2" = "3",
                                   "3" = c("4", "5")))


skimr::skim (df2)
highcor <- df %>%
  dplyr::select(pred) %>%
  #mutate(contract = ifelse (contract == "1+2", "2", contract))%>%
  correlation(method = "auto") %>%
  as.data.frame() %>%
  group_by(Parameter1) %>%
  summarize (highcor = mean (r))
```

```{r}
# NDI T2 as outcome ------------------------------------------------------------
df3 <- df2 %>%
  mutate (outcome = ifelse (df$ndi_t2<5, 0, 1))  %>%
  mutate_at(vars(fac_var), factor)

fullmodel <- glm(outcome ~ ., data = df3, family = binomial())
nullmodel <- glm(outcome ~ 1, data = df3, family = binomial())

m1 <- boot.stepAIC (object = nullmodel,
                    data = df3,
                    direction = "both",
                    B = 1000 ,
                    alpha = 0.05,
                    seed = 123,
                    scope=list(upper=fullmodel ,lower=nullmodel))

m1
summary (m1$OrigStepAIC)

sim <- simulateResiduals(m1$OrigStepAIC)
plot(sim)
# NDI T3 as outcome ------------------------------------------------------------

df3 <- df2 %>%
  mutate (outcome = ifelse (df$ndi_t3<5, 0, 1))  %>%
  mutate_at(vars(fac_var), factor)

fullmodel <- glm(outcome ~ ., data = df3, family = binomial())
nullmodel <- glm(outcome ~ 1, data = df3, family = binomial())

m2 <- boot.stepAIC (object = nullmodel,
                    data = df3,
                    direction = "both",
                    B = 1000 ,
                    alpha = 0.05,
                    seed = 123,
                    scope=list(upper=fullmodel ,lower=nullmodel))

m2
summary (m2$OrigStepAIC)

sim <- simulateResiduals(m2$OrigStepAIC)
plot(sim)

# REC T2 as outcome ------------------------------------------------------------

df3 <- df2 %>%
  mutate (outcome = ifelse (df$rec_t2>90, 0, 1))  %>%
  mutate_at(vars(fac_var), factor)

fullmodel <- glm(outcome ~ ., data = df3, family = binomial())
nullmodel <- glm(outcome ~ 1, data = df3, family = binomial())

m3 <- boot.stepAIC (object = nullmodel,
                    data = df3,
                    direction = "both",
                    B = 1000 ,
                    alpha = 0.05,
                    seed = 123,
                    scope=list(upper=fullmodel ,lower=nullmodel))

m3
summary (m3$OrigStepAIC)

sim <- simulateResiduals(m3$OrigStepAIC)
plot(sim)

# REC T3 as outcome ------------------------------------------------------------

df3 <- df2 %>%
  mutate (outcome = ifelse (df$rec_t3>90, 0, 1))  %>%
  mutate_at(vars(fac_var), factor)

fullmodel <- glm(outcome ~ ., data = df3, family = binomial())
nullmodel <- glm(outcome ~ 1, data = df3, family = binomial())

m4 <- boot.stepAIC (object = nullmodel,
                    data = df3,
                    direction = "both",
                    B = 1000 ,
                    alpha = 0.05,
                    seed = 123,
                    scope=list(upper=fullmodel ,lower=nullmodel))

m4
summary (m4$OrigStepAIC)

sim <- simulateResiduals(m4$OrigStepAIC)
plot(sim)

res <- list(m1 = m1,
            m2 = m2,
            m3 = m3,
            m4 = m4)

saveRDS(res, "output/yol_res.RDS")

```


## Results

```{r}
res <- readRDS("output/yol_res.RDS")
list2env(res,globalenv())
```

### Export tables

## Demographics

```{r}
## Table 1 ---------------------------------------------------------------------

facs <- c("gender",
          "sick_leave",
          "contract",
          "rx",
          "education")

df_d <- df %>%
  mutate(education = factor (education)) %>%
  mutate (education = fct_collapse(education,
                                   "1" = c("1", "2"),
                                   "2" = "3",
                                   "3" = c("4", "5"))) %>%
  dplyr::select(c(names(df2), "ndi_t2", "ndi_t3", "rec_t2", "rec_t3")) %>%
  mutate (gender = factor (gender, 
                           labels = c("Female", "Male")),
          sick_leave = factor (sick_leave,
                                 labels = c("Retired", "Yes", "No")),
          contract = factor (contract,
                             labels = c("Unemployed", "Freelance", "Employed")),
          rx = factor (rx,
                       labels = c("No treatment", "Pharmacological & PT", 
                                         "PT", "PT & Alternative")),
          education = factor (education,
                              labels = c("Higher", "Moderate", "Lower"))
  )

new_head <- c("Gender",
              "Age (yrs)",
              "Sick leave",
              "Contract",
              "Accident weeks",
              "Treatment",
              "Education",
              "Pain intensity (0-100",
              "Recovery expectation",
              "LOT-R",
              "CDSE",
              "TSK",
              "PCS",
              "NDI",
              "NDI at T2",
              "NDI at T3",
              "Rec at T2",
              "Rec at T3")

names(df_d) <- new_head


descrb_df <- df_d %>%
  tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd})",
                     all_categorical() ~ "{n} / {N} ({p}%)"),
    missing_text = "Missing",
    digits = list(all_continuous() ~ c(2,2))) %>%
  bold_labels() %>%
  modify_header(label = "**Variable**") %>%
  #remove_row_type(type = "missing") %>%
  as_flex_table()

descrb_df


my_path <- paste0("data/table1",
                  ".docx")

ft <- descrb_df %>%
  set_caption(caption = "Table 1") %>%
  autofit()

my_doc <- read_docx()  %>%
  body_add_flextable(ft)

print (my_doc, target = my_path)

```


```{r}
# Figure 1a -------------------------------------------

regress1 <- ggcoef_model(m1$OrigStepAIC,
                         variable_labels = c(
                           ndi ~ "NDI",
                            pcs ~ "PCS",
                            age ~ "Age",
                            expect ~ "Expectation",
                            lotr ~ "LOT-R",
                            facet_row = NULL),
                         exponentiate = TRUE,
                         colour = NULL
                         ) +
  xlab ("Odds ratio") 


# Figure 1b -------------------------------------------

regress2 <- ggcoef_model(m2$OrigStepAIC,
                         variable_labels = c(
                           ndi ~ "NDI",
                            pcs ~ "PCS",
                            age ~ "Age",
                            facet_row = NULL),
                         exponentiate = TRUE,
                         colour = NULL
                         ) +
  xlab ("Odds ratio") + 
  theme(legend.position = "none")

# Figure 1c -------------------------------------------

regress3 <- ggcoef_model(m3$OrigStepAIC,
                         variable_labels = c(
                           expect ~ "Expectation",
                           ndi ~ "NDI",
                           cdse ~ "CDSE",
                            pcs ~ "PCS",
                           lotr ~ "LOT-R",
                            vas ~ "VAS",
                            facet_row = NULL),
                         exponentiate = TRUE,
                         colour = NULL
                         ) +
  xlab ("Odds ratio") + 
  theme(legend.position = "none")

# Figure 1d -------------------------------------------

regress4 <- ggcoef_model(m4$OrigStepAIC,
                         variable_labels = c(
                           expect ~ "Expectation",
                           ndi ~ "NDI",
                           cdse ~ "CDSE",
                            pcs ~ "PCS",
                           lotr ~ "LOT-R",
                            acc_wks ~ "Accident wks",
                            facet_row = NULL),
                         exponentiate = TRUE,
                         colour = NULL
                         ) +
  xlab ("Odds ratio") + 
  theme(legend.position = "none")

# extract the legend from one of the plots
legend <- get_legend(
  # create some space to the left of the legend
  regress1  +  theme(legend.position = "bottom")
)

prow <- plot_grid(regress1 + theme(legend.position="none"),
                  regress2,
                  regress3,
                  regress4,
                  ncol = 2,
                  nrow = 2,
                  labels = c("a", "b", "c", "d")
)
                  
                  
                  
                  
# add the legend to the row we made earlier. Give it one-third of 
# the width of one plot (via rel_widths).
tiff(width = 15, height = 10, units = "in", res = 100, file = "data/fig1.tiff")
plot_grid(prow, legend, ncol = 1, rel_heights = c(1, .1))
dev.off()
```

## Report

```{r}
t1 <- tbl_regression(m1$OrigStepAIC,
                     exponentiate = TRUE)
t1

t2 <- tbl_regression(m2$OrigStepAIC,
                     exponentiate = TRUE)
t2

t3 <- tbl_regression(m3$OrigStepAIC,
                     exponentiate = TRUE)
t3

t4 <- tbl_regression(m4$OrigStepAIC,
                     exponentiate = TRUE)
t4
```


## Plot frequency selection

```{r}
heat_df1 <- data.frame (Covariates = row.names (m1$Covariates),
                       NDI_T2 = m1$Covariates[,1])
heat_df2 <- data.frame (Covariates = row.names (m2$Covariates),
                        NDI_T3 = m2$Covariates[,1])
heat_df3 <- data.frame (Covariates = row.names (m3$Covariates),
                        Rec_T2 = m3$Covariates[,1])
heat_df4 <- data.frame (Covariates = row.names (m4$Covariates),
                        Rec_T3 = m4$Covariates[,1])

heat_df <- heat_df1 %>%
  inner_join(heat_df2, by = "Covariates") %>%
  inner_join(heat_df3, by = "Covariates") %>%
  inner_join(heat_df4, by = "Covariates") %>%
  mutate (Overall = (NDI_T2 + NDI_T3 + Rec_T2 + Rec_T3)/4) %>%
  pivot_longer(-Covariates,
               names_to = "Outcomes",
               values_to = "Freq") %>%
  mutate (Outcomes = factor (Outcomes, levels = c("NDI_T2", "NDI_T3", "Rec_T2", "Rec_T3", "Overall")))
 
f1 <- ggplot(heat_df, aes(Outcomes, Covariates, fill= Freq)) + 
  geom_tile() + 
  scale_fill_gradient(low="white", high="blue") +
  labs(fill = "Frequency(%)")
```

## Plot significance selection

```{r}
heat_df1 <- data.frame (Covariates = row.names (m1$Significance),
                       NDI_T2 = m1$Significance[,1])
heat_df2 <- data.frame (Covariates = row.names (m2$Significance),
                        NDI_T3 = m2$Significance[,1])
heat_df3 <- data.frame (Covariates = row.names (m3$Significance),
                        Rec_T2 = m3$Significance[,1])
heat_df4 <- data.frame (Covariates = row.names (m4$Significance),
                        Rec_T3 = m4$Significance[,1])

heat_df <- heat_df1 %>%
  inner_join(heat_df2, by = "Covariates") %>%
  inner_join(heat_df3, by = "Covariates") %>%
  inner_join(heat_df4, by = "Covariates") %>%
  mutate (Overall = (NDI_T2 + NDI_T3 + Rec_T2 + Rec_T3)/4) %>%
  pivot_longer(-Covariates,
               names_to = "Outcomes",
               values_to = "Freq") %>%
  mutate (Outcomes = factor (Outcomes, levels = c("NDI_T2", "NDI_T3", "Rec_T2", "Rec_T3", "Overall")))
 
 
f2 <- ggplot(heat_df, aes(Outcomes, Covariates, fill= Freq)) + 
  geom_tile() + 
  scale_fill_gradient(low="white", high="blue") +
  labs(fill = "Frequency(%)")
```

## Plot coefficient sign

```{r}
heat_df1 <- data.frame (Covariates = row.names (m1$Sign),
                       NDI_T2 = m1$Sign[,1])
heat_df2 <- data.frame (Covariates = row.names (m2$Sign),
                        NDI_T3 = m2$Sign[,1])
heat_df3 <- data.frame (Covariates = row.names (m3$Sign),
                        Rec_T2 = m3$Sign[,1])
heat_df4 <- data.frame (Covariates = row.names (m4$Sign),
                        Rec_T3 = m4$Sign[,1])

heat_df <- heat_df1 %>%
  inner_join(heat_df2, by = "Covariates") %>%
  inner_join(heat_df3, by = "Covariates") %>%
  inner_join(heat_df4, by = "Covariates") %>%
  mutate (Overall = (NDI_T2 + NDI_T3 + Rec_T2 + Rec_T3)/4) %>%
  pivot_longer(-Covariates,
               names_to = "Outcomes",
               values_to = "Freq") %>%
  mutate (Outcomes = factor (Outcomes, levels = c("NDI_T2", "NDI_T3", "Rec_T2", "Rec_T3", "Overall")))
 
 
 
f3 <- ggplot(heat_df, aes(Outcomes, Covariates, fill= Freq)) + 
  geom_tile() + 
  scale_fill_gradient(low="white", high="blue") +
  labs(fill = "Frequency(%)")

tiff(width = 10, height = 7, units = "in", res = 100, file = "data/fig2.tiff")

cowplot::plot_grid(f1, f2, 
                   labels = c("a", "b"),
                   ncol = 2)
dev.off()
```
